### ISSUE TITLE
Data being stored in the server ? Privacy ? 

### ISSUE THREAD

**Issue by shemul** [sagorbrur/shuddhi-app#1]
Impressive! But .. 

how the data is being used. Is the text stored in the server database? Also I don't see any privacy guideline sections

**Comment by sagorbrur** [comment]
Hi,
Thanks for raising the issue. 
At present, I am not storing any data right now. I am preparing the privacy policy. Will add it to the app soon. 

Regards

**Comment by sagorbrur** [comment]
Hi @shemul ,
Here is the privacy policy. Please have a look. 
[https://github.com/sagorbrur/shuddhi-app/blob/main/privacy-policy.md](https://github.com/sagorbrur/shuddhi-app/blob/main/privacy-policy.md)
Any suggestions or changes please feel free to share. 

Regards
Sagor

**Comment by sagorbrur** [comment]
Hi @shemul ,
I am hoping your question is answered with a privacy policy link. 
I am closing this issue.

Thanks again for raising this issue.
